// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    PostItem: typeof import("./src/components/PostList/PostItem.vue")["default"];
    PostList: typeof import("./src/components/PostList/PostList.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    TabBar: typeof import("./src/components/TabBar/TabBar.vue")["default"];
    VanDivider: typeof import("vant/es")["Divider"];
    VanTabbar: typeof import("vant/es")["Tabbar"];
    VanTabbarItem: typeof import("vant/es")["TabbarItem"];
  }
}
